[[plugins]]
repo = 'jiangmiao/auto-pairs'
on_i = 1

[[plugins]]
repo  = 'cespare/vim-toml'
on_ft = ['toml']
on_i  = 1

[[plugins]]
repo        = 'neoclide/coc.nvim'
merged      = '0'
rev         = 'release'
on_i        = 1
