[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo     = 'davidcelis/vim-ariake-dark'
hook_add = '''
  colorscheme Ariake-Dark
  set background=dark
'''

[[plugins]]
repo = 'vim-airline/vim-airline-themes'
