[[plugins]]
repo  = 'cespare/vim-toml'
on_ft = ['toml']
on_i  = 1

[[plugins]]
repo = 'Townk/vim-autoclose'
on_i = 1

[[plugins]]
repo        = 'neoclide/coc.nvim'
rev         = 'release'
on_i        = 1
merged      = '0'
hook_source = 'call coil398#init#coc#hook_source()'
